import { createContext, useContext, useState, type ReactNode } from 'react'

type Lang = 'cz' | 'en'

const LangContext = createContext<{
  lang: Lang
  t: (key: string) => string
  setLang: (l: Lang) => void
}>({
  lang: 'cz',
  t: (key: string) => key,
  setLang: () => {},
})

const STORAGE_KEY = 'norkuj-lang'

function getInitialLang(): Lang {
  const stored = localStorage.getItem(STORAGE_KEY)
  if (stored === 'en') return 'en'
  return 'cz'
}

const cs: Record<string, string> = {
  'favorites_title': 'Oblíbené',
  'favorites_empty': 'Zatím nemáš žádné oblíbené inzeráty.',
  'favorites_back': '← Zpět',
  'profile': 'Profil',
  'logout': 'Odhlásit',
  'login': 'Přihlásit',
  'register': 'Registrovat',
  'add_listing': '+ Přidat',
  'my_listings': 'Moje inzerce',
  'search_hint': 'Vyber linky, oblasti nebo filtry...',
  'listings_count': 'inzerátů',
  'metro_label': 'Metro',
  'tram_label': 'Tramvaj',
  'district_label': 'Oblast / čtvrť',
  'map_filter_label': '🗺 Filtrovat dle pohybu mapy',
  'filters_label': 'Filtry',
  'hide_label': 'Skrýt',
  'reset_label': '✕ Resetovat vše',
  'green': 'V obou oblastech',
  'yellow': 'Jen v městské části',
  'red': 'Jen na trase linek',
  'grey': 'Ostatní',
  'green_transit_only': 'V dosahu linky',
  'yellow_transit_only': 'Dále od linky',
  'yellow_dist_only': 'V městské části',
  'no_results': 'Žádné inzeráty',
  'no_results_hint': 'Zkus upravit filtry',
  'sort_date': 'Datum',
  'sort_price': 'Cena',
  'sort_area': 'Plocha',
  'iso_label': '📍 Dojezd PID (MHD)',
  'iso_description': 'reálný dosah z libovolného místa pomocí dopravy PID',
  'iso_active': 'klikni na mapu pro výpočet',
  'iso_cancel': '✕ Zrušit',
  'iso_minutes': 'min',
  'iso_loading': '⏳',
  'map_toggle_hide': '🗺 Skrýt mapu',
  'map_toggle_show': '🗺 Zobrazit mapu',
  'mobile_map_btn': '🗺 Mapa',
  'mobile_list_btn': '📋 Seznam',
  'mobile_list_btn_back': '← Seznam',
  'loading': 'Načítám...',
  'no_listings': 'Žádné inzeráty',
  'theme_light': 'Světlý režim',
  'theme_dark': 'Tmavý režim',
  'back_search': 'Zpět na vyhledávání',
  'multi_hint': 'lze vybrat víc',
  'amenities_furnished':'Zařízený',
  'amenities_pets': 'Zvířata',
  'amenities_parking': 'Parkování',
  'amenities_balcony': 'Balkon',
  'amenities_cellar': 'Sklep',
  'map_legend_both': 'V obou oblastech',
  'map_legend_district': 'Jen v městské části',
  'map_legend_line': 'Jen na trase linek',
  'map_legend_other': 'Ostatní',
  'filter_popup_title': 'Oblast / čtvrť',
  'listing_detail_close': '✕',
  'listing_detail_contact': '📞 Zobrazit kontakt',
  'listing_detail_login_prompt': 'Pro zobrazení kontaktu se přihlas zdarma',
  'listing_detail_login_btn': 'Přihlásit se',
  'listing_detail_location': 'Poloha na mapě',
  '_line': 'linka',
  '_lines': 'linky',
  '_district': 'oblast',
  '_districts': 'oblasti',
  'price_hint': 'Kč',
  'min_area_label': 'Min. plocha',
  'amenities_label': 'Vybavení',
  '_floorplan': 'Dispozice',
  '_rent': 'Nájem',
  '_donate': 'Podpořit',
  '_kofi_button': 'Podpořit',
  '_kofi_title': 'Podpoř Norkuj',
  '_kofi_fallback': 'Otevřít v novém okně →',
  '_copyright': 'norkuj · 🏡 Najdi své bydlení v Praze',
  '_made_by': 'Made by',
  '_footer_privacy': 'Ochrana osobních údajů',
  '_footer_cookies': 'Cookies',
  '_footer_terms': 'Podmínky služby',
  '_footer_consumer': 'Ochrana spotřebitele',
  '_detail_loading': 'Načítám inzerát...',
  '_detail_close': 'Zavřít',
  '_detail_floorplan': 'Dispozice',
  '_detail_area': 'Plocha',
  '_detail_floor': 'Patro',
  '_detail_available': 'Dostupné od',
  '_detail_min_lease': 'Min. nájem',
  '_detail_deposit': 'Kauce',
  '_detail_description': 'Popis',
  '_detail_owner': 'Majitel',
  '_detail_private': 'Soukromá osoba',
  '_detail_no_phone': 'Majitel neuvedl telefon',
  '_detail_contact_note': 'Kontaktuj přímo — žádná provize',
  '_detail_contact_btn': '📞 Zobrazit kontakt',
  '_detail_login_btn': 'Přihlásit se',
  '_detail_login_prompt': 'Pro zobrazení kontaktu se přihlas zdarma',
  '_detail_added': 'Přidáno',
  '_detail_location': 'Poloha na mapě',
  '_detail_month': 'měs.',
  '_detail_floor_prefix': '. patro',
  '_detail_share': 'Sdílet',
  '_detail_share_copied': 'Odkaz zkopírován!',
  '_cookies_title': 'Nastavení cookies',
  '_cookies_text': 'Používáme nezbytné cookies pro základní fungování a Google Analytics pro anonymní statistiky návštěvnosti. Analytické cookies se načítají pouze s vaším výslovným souhlasem.',
  '_cookies_link': 'Zásady cookies',
  '_cookies_accept': 'Přijmout',
  '_cookies_reject': 'Odmítnout',
  '_profile_title': 'Nastavení profilu',
  '_profile_email': 'Email',
  '_profile_name': 'Jméno',
  '_profile_phone': 'Telefon',
  '_profile_save': 'Uložit',
  '_profile_saving': 'Ukládám...',
  '_profile_saved': 'Uloženo.',
  '_profile_load': 'Načítám...',
  '_profile_back': '← Zpět',
  '_profile_delete_title': 'Smazat profil',
  '_profile_delete_warning': 'Varování:',
  '_profile_delete_text': 'Tato akce je nevratná. Smazáním profilu trvale odstraníš všechny své inzeráty, fotky a osobní údaje. Tuto akci nelze vrátit zpět.',
  '_profile_delete_cancel': 'Zrušit',
  '_profile_delete_confirm': 'Ano, smazat profil',
  '_profile_delete_progress': 'Mažu...',
  '_profile_delete_fail': 'Chyba při mazání profilu',
  '_tour_title': 'Jak to funguje',
  '_tour_prev': 'Zpět',
  '_tour_next': 'Další',
  '_tour_done': 'Hotovo',
  '_tour_placeholder': 'Video bude brzy k dispozici',
  '_tour_slide1_title': 'Najdi své bydlení',
  '_tour_slide1_desc': 'Prohlížej nabídky bytů a sdíleného bydlení v Praze. Filtruj podle lokality, ceny, vybavení a dostupnosti MHD.',
  '_tour_slide2_title': 'Filtruj podle MHD',
  '_tour_slide2_desc': 'Vyber metro nebo tram linku a ihned uvidíš, které nabídky jsou v dosahu. Barevné značení na mapě ukazuje kvalitu dopravního spojení.',
  '_tour_slide3_title': 'Dojezdová mapa',
  '_tour_slide3_desc': 'Klikni na libovolné místo na mapě a my spočítáme, kam se dostaneš MHD za 10, 20 nebo 30 minut. Ideální pro hledání bydlení s konkrétním dojezdem.',
  '_tour_slide4_title': 'Přidej vlastní inzerát',
  '_tour_slide4_desc': 'Máš volný byt nebo hledáš spolubydlení? Přidej inzerát zdarma, nahraj fotky a nastav polohu přímo na mapě.',
  '_tour_slide5_title': 'Okresní filtrování',
  '_tour_slide5_desc': 'Filtruj nejen podle pražských čtvrtí, ale i podle katastrálních území a městských částí. Každá nabídka je přesně přiřazena.',
  '_tour_slide6_title': 'Kontaktuj majitele',
  '_tour_slide6_desc': 'Po přihlášení uvidíš kontakt na majitele nebo pronajímatele. Žádná provize, vše napřímo.',

  '_auth_back': '← Zpět',
  '_auth_subtitle': 'Pronájem bez realitky',
  '_auth_tab_login': 'Přihlásit se',
  '_auth_tab_register': 'Registrovat',
  '_auth_recovery_title': 'Obnovit heslo',
  '_auth_email_placeholder': 'Email',
  '_auth_password_placeholder': 'Heslo',
  '_auth_name_placeholder': 'Jméno',
  '_auth_phone_placeholder': 'Telefon (+420...)',
  '_auth_forgot': 'Zapomenuté heslo?',
  '_auth_submit_login': 'Přihlásit se',
  '_auth_submit_register': 'Vytvořit účet',
  '_auth_submit_reset': 'Poslat odkaz na obnovu',
  '_auth_reset_title': 'Nastav nové heslo',
  '_auth_newpassword_placeholder': 'Nové heslo',
  '_auth_submit_newpassword': 'Uložit nové heslo',
  '_auth_back_to_login': '← Zpět na přihlášení',
  '_auth_or': 'nebo',
  '_auth_google': 'Pokračovat přes Google',
  '_auth_error_invalid': 'Špatný email nebo heslo.',
  '_auth_register_success': 'Zkontroluj email a potvrď registraci.',
  '_auth_reset_sent': 'Poslali jsme ti email s odkazem na obnovu hesla.',
  '_auth_password_changed': 'Heslo změněno. Přesměrovávám...',

  '_create_step0': 'Základní info',
  '_create_step1': 'Cena & detaily',
  '_create_step2': 'Poloha na mapě',
  '_create_step3': 'Fotografie',
  '_create_step4': 'Přehled',
  '_create_title_label': 'Název inzerátu *',
  '_create_title_placeholder': 'Světlý byt 2+kk v centru Prahy',
  '_create_desc_label': 'Popis *',
  '_create_desc_placeholder': 'Popište byt, lokalitu, dostupnost MHD...',
  '_create_type_label': 'Typ nabídky *',
  '_create_room_hint': 'Pokoj ve sdíleném bytě — vhodné pro spolubydlení.',
  '_create_area_label': 'Plocha (m²) *',
  '_create_floor_label': 'Patro',
  '_create_available_label': 'Dostupné od *',
  '_create_furnished': 'Zařízený',
  '_create_pets': 'Zvířata OK',
  '_create_parking': 'Parkování',
  '_create_balcony': 'Balkon',
  '_create_cellar': 'Sklep',
  '_create_price_label': 'Nájemné (Kč/měs) *',
  '_create_utilities_label': 'Zálohy / služby (Kč/měs)',
  '_create_deposit_label': 'Kauce (Kč)',
  '_create_minlease_label': 'Min. délka nájmu (měsíce)',
  '_create_total': 'Celkem:',
  '_create_street_label': 'Ulice a číslo *',
  '_create_street_placeholder': 'Mánesova 12, Vinohrady',
  '_create_map_label': 'Přesná poloha — klikni na mapu *',
  '_create_map_done': '✓ Poloha označena',
  '_create_map_hint': 'Klikni na mapu pro označení polohy',
  '_create_district_label': 'Čtvrť / Část Prahy *',
  '_create_district_hint': 'lze vybrat 1–2',
  '_create_district_empty': 'Vyber alespoň 1 oblast',
  '_create_found': 'Našli jsme:',
  '_create_photos_label': 'Fotografie (max 20)',
  '_create_photos_hint': 'Klikni nebo přetáhni fotky',
  '_create_review_title': 'Přehled inzerátu',
  '_create_edit_warning': '⚠️ Úprava inzerátu vyžaduje opětovné schválení administrátorem. Inzerát dočasně zmizí z vyhledávání, dokud ho znovu neschválíme.',
  '_create_review_name': 'Název',
  '_create_review_type': 'Typ',
  '_create_review_area': 'Plocha',
  '_create_review_price': 'Nájemné',
  '_create_review_utilities': 'Zálohy',
  '_create_review_address': 'Adresa',
  '_create_review_location': 'Poloha',
  '_create_review_photos': 'Fotky',
  '_create_review_ok': '✓ Označena',
  '_create_review_missing': '✗ Chybí',
  '_create_nav_cancel': 'Zrušit',
  '_create_nav_back': '← Zpět',
  '_create_nav_next': 'Pokračovat →',
  '_create_submit': 'Odeslat ke kontrole',
  '_create_submit_edit': 'Uložit a poslat ke kontrole',
  '_create_submitting': 'Odesílám...',
  '_create_success_title': 'Inzerát odeslán ke kontrole',
  '_create_success_title_edit': 'Úprava odeslána ke kontrole',
  '_create_success_text': 'Zkontrolujeme ho a brzy zveřejníme. Dostaneš email s potvrzením.',
  '_create_success_text_edit': 'Zkontrolujeme změny a brzy je znovu zveřejníme. Dostaneš email s potvrzením.',
  '_create_back_home': 'Zpět na hlavní stránku',
  '_create_confirm_title': 'Rozpracovaný inzerát se neuloží. Opravdu chceš zavřít?',
  '_create_confirm_continue': 'Pokračovat v editaci',
  '_create_confirm_discard': 'Zahodit a zavřít',
  '_create_error_auth': 'Nejsi přihlášen',
  '_create_error_location': 'Vyber polohu na mapě',
  '_create_error_upload': 'Nahrávání fotky selhalo: ',
  '_create_error_save': 'Chyba při ukládání',

  '_mylistings_back': '← Zpět',
  '_mylistings_title': 'Moje inzeráty',
  '_mylistings_empty': 'Zatím nemáš žádné inzeráty.',
  '_mylistings_status_draft': 'Koncept',
  '_mylistings_status_pending': 'Čeká na schválení',
  '_mylistings_status_published': 'Zveřejněno',
  '_mylistings_status_rented': 'Pronajato',
  '_mylistings_status_rejected': 'Zamítnuto',
  '_mylistings_status_deleted': 'Smazáno',
  '_mylistings_edit': 'Upravit',
  '_mylistings_mark_rented': 'Pronajato',
  '_mylistings_delete': 'Smazat',
  '_mylistings_confirm_delete': 'Opravdu chceš tento inzerát smazat? Tato akce je nevratná.',
  '_mylistings_rejection_reason': 'Důvod zamítnutí:',
  '_mylistings_added': 'přidáno',

  '_admin_panel': '🛠 Admin panel',
  '_admin_tab_pending': 'Čeká na schválení',
  '_admin_tab_published': 'Zveřejněné',
  '_admin_tab_rejected': 'Zamítnuté',
  '_admin_tab_all': 'Všechny',
  '_admin_empty': 'Žádné inzeráty v této kategorii',
  '_admin_status_pending': 'Čeká',
  '_admin_status_published': 'Zveřejněn',
  '_admin_status_rejected': 'Zamítnut',
  '_admin_status_draft': 'Koncept',
  '_admin_status_deleted': 'Smazán',
  '_admin_no_phone': 'bez tel.',
  '_admin_detail_owner': 'Majitel',
  '_admin_detail_phone': 'Telefon',
  '_admin_detail_type': 'Dispozice',
  '_admin_detail_area': 'Plocha',
  '_admin_detail_price': 'Cena',
  '_admin_detail_status': 'Status',
  '_admin_detail_added': 'Přidáno',
  '_admin_detail_id': 'ID',
  '_admin_detail_photos': 'Fotky',
  '_admin_approve': '✅ Schválit a zveřejnit',
  '_admin_approve_acting': 'Zpracovávám...',
  '_admin_reject_label': 'Důvod zamítnutí (povinné)...',
  '_admin_reject': 'Zamítnout',
  '_admin_unpublish': '⏸ Stáhnout z nabídky',
  '_admin_delete': '🗑 Trvale smazat',
  '_admin_confirm_delete': 'Opravdu smazat?',
  '_admin_select_prompt': 'Vyber inzerát ze seznamu',
  '_admin_no_access': 'Nemáš přístup do admin panelu.',
  '_admin_close': 'Zavřít',
  '_admin_msg_published': '✅ Inzerát zveřejněn',
  '_admin_msg_rejected': '❌ Inzerát zamítnut',
  '_admin_msg_deleted': '🗑 Smazáno',
  '_admin_msg_reject_needed': 'Zadej důvod zamítnutí',
  '_admin_error': 'Chyba: ',
}

const en: Record<string, string> = {
  'favorites_title': 'Favorites',
  'favorites_empty': 'You don\'t have any favorite listings yet.',
  'favorites_back': '← Back',
  'profile': 'Profile',
  'logout': 'Log out',
  'login': 'Log in',
  'register': 'Register',
  'add_listing': '+ Add',
  'my_listings': 'My listings',
  'search_hint': 'Select lines, areas or filters...',
  'listings_count': 'listings',
  'metro_label': 'Metro',
  'tram_label': 'Tram',
  'district_label': 'District / quarter',
  'map_filter_label': '🗺 Filter by map view',
  'filters_label': 'Filters',
  'hide_label': 'Hide',
  'reset_label': '✕ Reset all',
  'green': 'In both areas',
  'yellow': 'In district only',
  'red': 'Near transit line only',
  'grey': 'Other',
  'green_transit_only': 'Near transit line',
  'yellow_transit_only': 'Further from line',
  'yellow_dist_only': 'In district',
  'no_results': 'No listings',
  'no_results_hint': 'Try adjusting filters',
  'sort_date': 'Date',
  'sort_price': 'Price',
  'sort_area': 'Area',
  'iso_label': '📍 Transit reach (PID)',
  'iso_description': 'reachable area via public transit',
  'iso_active': 'click on map to calculate',
  'iso_cancel': '✕ Cancel',
  'iso_minutes': 'min',
  'iso_loading': '⏳',
  'map_toggle_hide': '🗺 Hide map',
  'map_toggle_show': '🗺 Show map',
  'mobile_map_btn': '🗺 Map',
  'mobile_list_btn': '📋 List',
  'mobile_list_btn_back': '← List',
  'loading': 'Loading...',
  'no_listings': 'No listings',
  'theme_light': 'Light mode',
  'theme_dark': 'Dark mode',
  'back_search': 'Back to search',
  'multi_hint': 'select multiple',
  'amenities_furnished': 'Furnished',
  'amenities_pets': 'Pets OK',
  'amenities_parking': 'Parking',
  'amenities_balcony': 'Balcony',
  'amenities_cellar': 'Cellar',
  'map_legend_both': 'In both areas',
  'map_legend_district': 'In district only',
  'map_legend_line': 'Near transit line only',
  'map_legend_other': 'Other',
  'filter_popup_title': 'District / quarter',
  'listing_detail_close': '✕',
  'listing_detail_contact': '📞 Show contact',
  'listing_detail_login_prompt': 'Sign in for free to see contact',
  'listing_detail_login_btn': 'Sign in',
  'listing_detail_location': 'Location on map',
  '_line': 'line',
  '_lines': 'lines',
  '_district': 'area',
  '_districts': 'areas',
  'price_hint': 'CZK',
  'min_area_label': 'Min. area',
  'amenities_label': 'Amenities',
  '_floorplan': 'Layout',
  '_rent': 'Rent',
  '_donate': 'Support',
  '_kofi_button': 'Support',
  '_kofi_title': 'Support Norkuj',
  '_kofi_fallback': 'Open in new tab →',
  '_copyright': 'norkuj · 🏡 Find your home in Prague',
  '_made_by': 'Made by',
  '_footer_privacy': 'Privacy Policy',
  '_footer_cookies': 'Cookies',
  '_footer_terms': 'Terms of Service',
  '_footer_consumer': 'Consumer Protection',
  '_detail_loading': 'Loading listing...',
  '_detail_close': 'Close',
  '_detail_floorplan': 'Layout',
  '_detail_area': 'Area',
  '_detail_floor': 'Floor',
  '_detail_available': 'Available from',
  '_detail_min_lease': 'Min. lease',
  '_detail_deposit': 'Deposit',
  '_detail_description': 'Description',
  '_detail_owner': 'Owner',
  '_detail_private': 'Private person',
  '_detail_no_phone': 'Owner did not provide a phone number',
  '_detail_contact_note': 'Contact directly — no commission',
  '_detail_contact_btn': '📞 Show contact',
  '_detail_login_btn': 'Sign in',
  '_detail_login_prompt': 'Sign in for free to see contact',
  '_detail_added': 'Added',
  '_detail_location': 'Location on map',
  '_detail_month': 'mo.',
  '_detail_floor_prefix': 'th floor',
  '_detail_share': 'Share',
  '_detail_share_copied': 'Link copied!',
  '_cookies_title': 'Cookie Consent',
  '_cookies_text': 'We use essential cookies for basic functionality and Google Analytics for anonymous usage statistics. Analytics cookies are only loaded with your explicit consent.',
  '_cookies_link': 'Cookie Policy',
  '_cookies_accept': 'Accept',
  '_cookies_reject': 'Reject',
  '_profile_title': 'Profile Settings',
  '_profile_email': 'Email',
  '_profile_name': 'Name',
  '_profile_phone': 'Phone',
  '_profile_save': 'Save',
  '_profile_saving': 'Saving...',
  '_profile_saved': 'Saved.',
  '_profile_load': 'Loading...',
  '_profile_back': '← Back',
  '_profile_delete_title': 'Delete profile',
  '_profile_delete_warning': 'Warning:',
  '_profile_delete_text': 'This action is permanent and cannot be undone. Deleting your profile will permanently remove all your listings, photos and personal data.',
  '_profile_delete_cancel': 'Cancel',
  '_profile_delete_confirm': 'Yes, delete profile',
  '_profile_delete_progress': 'Deleting...',
  '_profile_delete_fail': 'Failed to delete profile',
  '_tour_title': 'How it works',
  '_tour_prev': 'Back',
  '_tour_next': 'Next',
  '_tour_done': 'Done',
  '_tour_placeholder': 'Video coming soon',
  '_tour_slide1_title': 'Find your home',
  '_tour_slide1_desc': 'Browse apartment and shared-living listings in Prague. Filter by location, price, amenities and transit accessibility.',
  '_tour_slide2_title': 'Filter by transit',
  '_tour_slide2_desc': 'Select a metro or tram line and instantly see which listings are nearby. Color-coded markers on the map show transit quality.',
  '_tour_slide3_title': 'Transit reach map',
  '_tour_slide3_desc': 'Click anywhere on the map and we\'ll calculate the area reachable by public transit in 10, 20, or 30 minutes. Perfect for finding places with a specific commute.',
  '_tour_slide4_title': 'Add your own listing',
  '_tour_slide4_desc': 'Have a free apartment or looking for a roommate? Add a listing for free, upload photos and set the location right on the map.',
  '_tour_slide5_title': 'District filtering',
  '_tour_slide5_desc': 'Filter not only by Prague quarters but also by cadastral areas and administrative districts. Every listing is precisely assigned.',
  '_tour_slide6_title': 'Contact the owner',
  '_tour_slide6_desc': 'After signing in, you\'ll see the owner\'s contact. No commission, all direct.',

  '_auth_back': '← Back',
  '_auth_subtitle': 'Rent without agency',
  '_auth_tab_login': 'Log in',
  '_auth_tab_register': 'Register',
  '_auth_recovery_title': 'Reset password',
  '_auth_email_placeholder': 'Email',
  '_auth_password_placeholder': 'Password',
  '_auth_name_placeholder': 'Name',
  '_auth_phone_placeholder': 'Phone (+420...)',
  '_auth_forgot': 'Forgot password?',
  '_auth_submit_login': 'Log in',
  '_auth_submit_register': 'Create account',
  '_auth_submit_reset': 'Send recovery link',
  '_auth_reset_title': 'Set new password',
  '_auth_newpassword_placeholder': 'New password',
  '_auth_submit_newpassword': 'Save new password',
  '_auth_back_to_login': '← Back to login',
  '_auth_or': 'or',
  '_auth_google': 'Continue with Google',
  '_auth_error_invalid': 'Invalid email or password.',
  '_auth_register_success': 'Check your email to confirm registration.',
  '_auth_reset_sent': 'We\'ve sent you an email with a password recovery link.',
  '_auth_password_changed': 'Password changed. Redirecting...',

  '_create_step0': 'Basic info',
  '_create_step1': 'Price & details',
  '_create_step2': 'Location on map',
  '_create_step3': 'Photos',
  '_create_step4': 'Review',
  '_create_title_label': 'Listing title *',
  '_create_title_placeholder': 'Bright 2+kk apartment in central Prague',
  '_create_desc_label': 'Description *',
  '_create_desc_placeholder': 'Describe the apartment, area, transit access...',
  '_create_type_label': 'Property type *',
  '_create_room_hint': 'Room in a shared apartment — suitable for flat-sharing.',
  '_create_area_label': 'Area (m²) *',
  '_create_floor_label': 'Floor',
  '_create_available_label': 'Available from *',
  '_create_furnished': 'Furnished',
  '_create_pets': 'Pets OK',
  '_create_parking': 'Parking',
  '_create_balcony': 'Balcony',
  '_create_cellar': 'Cellar',
  '_create_price_label': 'Rent (CZK/month) *',
  '_create_utilities_label': 'Utilities / service fees (CZK/month)',
  '_create_deposit_label': 'Deposit (CZK)',
  '_create_minlease_label': 'Min. lease (months)',
  '_create_total': 'Total:',
  '_create_street_label': 'Street & number *',
  '_create_street_placeholder': 'Mánesova 12, Vinohrady',
  '_create_map_label': 'Exact location — click on the map *',
  '_create_map_done': '✓ Location set',
  '_create_map_hint': 'Click on the map to set location',
  '_create_district_label': 'District / Prague quarter *',
  '_create_district_hint': 'select 1–2',
  '_create_district_empty': 'Select at least 1 area',
  '_create_found': 'We found:',
  '_create_photos_label': 'Photos (max 20)',
  '_create_photos_hint': 'Click or drag photos here',
  '_create_review_title': 'Listing review',
  '_create_edit_warning': '⚠️ Editing a listing requires re-approval by an admin. The listing will temporarily disappear from search until re-approved.',
  '_create_review_name': 'Name',
  '_create_review_type': 'Type',
  '_create_review_area': 'Area',
  '_create_review_price': 'Rent',
  '_create_review_utilities': 'Utilities',
  '_create_review_address': 'Address',
  '_create_review_location': 'Location',
  '_create_review_photos': 'Photos',
  '_create_review_ok': '✓ Set',
  '_create_review_missing': '✗ Missing',
  '_create_nav_cancel': 'Cancel',
  '_create_nav_back': '← Back',
  '_create_nav_next': 'Continue →',
  '_create_submit': 'Submit for review',
  '_create_submit_edit': 'Save and submit for review',
  '_create_submitting': 'Submitting...',
  '_create_success_title': 'Listing submitted for review',
  '_create_success_title_edit': 'Edit submitted for review',
  '_create_success_text': 'We\'ll review it and publish it soon. You\'ll get a confirmation email.',
  '_create_success_text_edit': 'We\'ll review the changes and re-publish them soon. You\'ll get a confirmation email.',
  '_create_back_home': 'Back to homepage',
  '_create_confirm_title': 'Your draft will be lost. Are you sure you want to close?',
  '_create_confirm_continue': 'Keep editing',
  '_create_confirm_discard': 'Discard and close',
  '_create_error_auth': 'You are not logged in',
  '_create_error_location': 'Select a location on the map',
  '_create_error_upload': 'Photo upload failed: ',
  '_create_error_save': 'Error saving',

  '_mylistings_back': '← Back',
  '_mylistings_title': 'My listings',
  '_mylistings_empty': 'You don\'t have any listings yet.',
  '_mylistings_status_draft': 'Draft',
  '_mylistings_status_pending': 'Pending review',
  '_mylistings_status_published': 'Published',
  '_mylistings_status_rented': 'Rented',
  '_mylistings_status_rejected': 'Rejected',
  '_mylistings_status_deleted': 'Deleted',
  '_mylistings_edit': 'Edit',
  '_mylistings_mark_rented': 'Mark as rented',
  '_mylistings_delete': 'Delete',
  '_mylistings_confirm_delete': 'Are you sure you want to delete this listing? This action cannot be undone.',
  '_mylistings_rejection_reason': 'Rejection reason:',
  '_mylistings_added': 'added',

  '_admin_panel': '🛠 Admin panel',
  '_admin_tab_pending': 'Pending review',
  '_admin_tab_published': 'Published',
  '_admin_tab_rejected': 'Rejected',
  '_admin_tab_all': 'All',
  '_admin_empty': 'No listings in this category',
  '_admin_status_pending': 'Pending',
  '_admin_status_published': 'Published',
  '_admin_status_rejected': 'Rejected',
  '_admin_status_draft': 'Draft',
  '_admin_status_deleted': 'Deleted',
  '_admin_no_phone': 'no phone',
  '_admin_detail_owner': 'Owner',
  '_admin_detail_phone': 'Phone',
  '_admin_detail_type': 'Type',
  '_admin_detail_area': 'Area',
  '_admin_detail_price': 'Price',
  '_admin_detail_status': 'Status',
  '_admin_detail_added': 'Added',
  '_admin_detail_id': 'ID',
  '_admin_detail_photos': 'Photos',
  '_admin_approve': '✅ Approve & publish',
  '_admin_approve_acting': 'Processing...',
  '_admin_reject_label': 'Rejection reason (required)...',
  '_admin_reject': 'Reject',
  '_admin_unpublish': '⏸ Remove from listings',
  '_admin_delete': '🗑 Permanently delete',
  '_admin_confirm_delete': 'Permanently delete?',
  '_admin_select_prompt': 'Select a listing from the list',
  '_admin_no_access': 'You don\'t have access to the admin panel.',
  '_admin_close': 'Close',
  '_admin_msg_published': '✅ Listing published',
  '_admin_msg_rejected': '❌ Listing rejected',
  '_admin_msg_deleted': '🗑 Deleted',
  '_admin_msg_reject_needed': 'Enter a rejection reason',
  '_admin_error': 'Error: ',
}

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(getInitialLang)

  const setLang = (l: Lang) => {
    setLangState(l)
    localStorage.setItem(STORAGE_KEY, l)
  }

  const t = (key: string): string => {
    const dict = lang === 'en' ? en : cs
    return dict[key] ?? key
  }

  return (
    <LangContext.Provider value={{ lang, t, setLang }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
